name: places
description: Путеводитель по интересным местам мира

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.0
  drift: ^2.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_svg: ^2.0.0
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  path: ^1.8.2
  path_provider: ^2.0.14
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  recase: ^4.1.0
  retrofit: ^4.0.1
  sqlite3_flutter_libs: ^0.5.13
  uuid: ^3.0.7
  verify: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4
  retrofit_generator: ^5.0.0
  surf_lint_rules: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/category/
    - assets/icons/empty/
    - assets/icons/menu/
    - assets/icons/tutorial/
    - assets/icons/splash_screen/

  fonts:
    - family: 'Roboto'
      fonts:
        - asset: 'assets/fonts/Roboto/Roboto-Regular.ttf'
          style: normal
        - asset: 'assets/fonts/Roboto/Roboto-Italic.ttf'
          style: italic
